### ISSUE TITLE
Example app confusion

### ISSUE THREAD

**Issue by cameron-erdogan** [spokestack/spokestack-ios#54]
Is there an explanation for what "SpokeStackFrameworkExample" app is supposed to be demonstrating? I see the four options on the initial landing page, and then start/stop recording buttons on each detail page. It asks for microphone access and sometimes speech access, but otherwise nothing seems to happen. There are some debug messages depending on whether I'm running iOS 12 or 13, but it's usually just "didStart" and "didStop".

**Comment by noelweichbrodt** [comment]
The example app’s purpose is to show developers an example of how to use the library and provide a record of events during the course of a run—hence all output is directed to the debug window. 

We are actively working on additional sample projects that will demonstrate more sophisticated integration of Spokestack than this built-in example app. An older but perhaps more helpful GUI example is available at https://github.com/pylon/spokestack-ios-example/tree/master/SpokeStackExample <https://github.com/pylon/spokestack-ios-example/tree/master/SpokeStackExample>.

**Comment by cameron-erdogan** [comment]
I tried running that one too, but it won't compile (on XCode 10.1). I get an error on "import SpokeStack" that says "Missing required module 'googleapis'".

Anyway, I can still try to use the main project to try to understand how I might use this in an app I'm developing. Should I expect to see more than just "didInit" and "didStart"?

**Comment by noelweichbrodt** [comment]
> Anyway, I can still try to use the main project to try to understand how I might use this in an app I'm developing. Should I expect to see more than just "didInit" and "didStart"?

`didInit` -> `didStart` -> `didActivate` (upon wakeword activation) -> `didRecognize` (upon ASR recognition)

The wakeword depends on which wakeword view controller is chosen. TFLite is "Marvin", Apple and CoreML is "Up dog".

Better API documentation is on the way, but for now https://github.com/pylon/react-native-spokestack/#api can provide a rough guide. The example app's controllers contain all the possible events: https://github.com/pylon/spokestack-ios/blob/master/SpokeStackFrameworkExample/WakeWordViewController.swift#L115.

HTH!

**Comment by cameron-erdogan** [comment]
Okay, that makes sense based on what I'm seeing in the code. I'm seeing bu `didStart` can't get `didActivate` to trigger after saying "Up dog". Is it necessary to press the start recording button? Either way it doesn't seem to help.

**Comment by noelweichbrodt** [comment]
It’s necessary to press “start recording” button in the example app. I recommend experimenting with the “Apple Wakeword” option first, the debug console output from that will be more useful in understanding the API.

**Comment by cameron-erdogan** [comment]
Okay I can spend some more time with that. Thanks for your help so far. 
 
Honestly I'm most interested with the VAD part of this code, since I haven't found a good iOS option for VAD. Any recommendations for using just that part in a separate module? I can also just ask that in a separate manner (not on this issue thread).

**Comment by noelweichbrodt** [comment]
Oh interesting that VAD for iOS is of interest. I was in the same place as you and ended up putting a fair bit of work into porting Google’s WebRTC VAD into Swift and buildable via CocoaPods. You can check out the Swift wrapper https://github.com/pylon/spokestack-ios/blob/master/SpokeStack/WebRTCVAD.swift <https://github.com/pylon/spokestack-ios/blob/master/SpokeStack/WebRTCVAD.swift> and the WebRTC audio port https://github.com/pylon/filter_audio <https://github.com/pylon/filter_audio>.

**Comment by cameron-erdogan** [comment]
Yep I saw that. Seems to be exactly what I'm looking for. Of course, I'm having some trouble building. 

My caveat is that my current deployment process uses Carthage instead of CocoaPods. So, I'm trying to include the relevant code by using the filter_audio framework from the example project's Pods > Frameworks folder and by directly including the relevant Swift wrapper code directly in my project. Things are working mostly okay, except I get a few `Undefined Symbol: _WebRtcVad_Process` errors when trying to build. I'm learning about including C projects as I go here, so I'm in slightly over my head. 

If I fail at this for a few more hours I may give up this path and try again just using CocoaPods.

**Comment by noelweichbrodt** [comment]
>  I get a few Undefined Symbol: _WebRtcVad_Process errors when trying to build.

This would indicate that the `webrtc_vad.h` header isn’t visible to the build path. I don’t know how Carthage works, but the general idea is to make sure that `ld` and `clang` are getting a good header search path to find the `filter_audio` headers, like https://github.com/pylon/filter_audio/blob/cocoapods/filter_audio.podspec#L18 <https://github.com/pylon/filter_audio/blob/cocoapods/filter_audio.podspec#L18>

**Comment by cameron-erdogan** [comment]
I should clarify, I'm not even using Carthage for this, I just have a vanilla project (not workspace) with filter_audio included as a regular framework. I only mentioned Carthage to explain my reluctance to include the framework with CocoaPods.

I seem to have gotten it to build, so I'll update you once I hook up some audio.

**Comment by cameron-erdogan** [comment]
After playing around with the example more: in the Apple Wakeword example, it seems the result of the `WebRtcVad_Process` in WebRTCVAD.swift is always either 0 (None) or 1 (Uncertain). The breakdown depends on the mode setting. In the "aggressive" mode, it distinguishes pretty well between noise and silence. It doesn't seem to differentiate between non-vocal noise and vocal noise, though. Is this expected? Or is it unusual for the detector to have such apparent low certainty?

**Comment by noelweichbrodt** [comment]
Sorry, thought I responded earlier! The vocal-vs-nonvocal is due to how a VAD works—it's purely dependent on frequencies in the vocal range.

Closing this issue, but feel free to comment if you have any more questions!
